// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF-VdzgtB6iEp8IeDQ7A3S-ArNcRUSEfs',
    appId: '1:754918591290:web:9d3337fb27194f4179de03',
    messagingSenderId: '754918591290',
    projectId: 'mynotes-66ff6',
    authDomain: 'mynotes-66ff6.firebaseapp.com',
    storageBucket: 'mynotes-66ff6.appspot.com',
    measurementId: 'G-T279J27W33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDog6-wbjp5ZWP9rAs4GnOxGeMs4xyAxIU',
    appId: '1:754918591290:android:dfb3faec0cdf6e6a79de03',
    messagingSenderId: '754918591290',
    projectId: 'mynotes-66ff6',
    storageBucket: 'mynotes-66ff6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFcMJ2ULllZ6Ao05ebljjqRrvWSrQgdEk',
    appId: '1:754918591290:ios:175f6e0cb9be496379de03',
    messagingSenderId: '754918591290',
    projectId: 'mynotes-66ff6',
    storageBucket: 'mynotes-66ff6.appspot.com',
    iosClientId: '754918591290-8es1advgukm28ti5joqa98pjikf6jg8m.apps.googleusercontent.com',
    iosBundleId: 'com.samad.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFcMJ2ULllZ6Ao05ebljjqRrvWSrQgdEk',
    appId: '1:754918591290:ios:27ee57062ea7ced779de03',
    messagingSenderId: '754918591290',
    projectId: 'mynotes-66ff6',
    storageBucket: 'mynotes-66ff6.appspot.com',
    iosClientId: '754918591290-q9u8f4jk7892l8iff4rkj6md85eg9p2j.apps.googleusercontent.com',
    iosBundleId: 'com.samad.mynotes.RunnerTests',
  );
}
